import { getHelperBotResponse } from '../../chatbot.js';

/**
 * Commodity ticker data.
 *
 * NOTE: these figures are generated by an LLM, not fetched from a market
 * data feed. They are indicative only. Replacing this with a real feed is
 * tracked in the audit (§8).
 */

export interface MarketData {
  insights: string[];
  commodities: {
    symbol: string;
    name: string;
    price: string;
    trend: string;
    up: boolean;
  }[];
}

const CACHE_TTL_MS = 1000 * 60 * 60; // 1 hour

let cached: MarketData | null = null;
let lastFetchedAt = 0;

export const OFFLINE_FALLBACK: MarketData = {
  insights: ['Global market telemetry temporarily offline.'],
  commodities: [
    { symbol: 'LME.Cu', name: 'Copper (Grade A)', price: '₹---', trend: '0.0%', up: true },
    { symbol: 'LME.Al', name: 'Primary Alum', price: '₹---', trend: '0.0%', up: true },
    { symbol: 'IDX.PVC', name: 'PVC Resin', price: '₹---', trend: '0.0%', up: true },
    { symbol: 'IDX.STL', name: 'Galv Steel', price: '₹---', trend: '0.0%', up: true },
  ],
};

const PROMPT = `You are a live financial API. Output a strict JSON object containing two keys:
1. "insights": An array of exactly 4 short, distinct sentences (max 20 words each) about current global macroeconomic trends for Copper, Aluminum, and PVC resin.
2. "commodities": An array of exactly 4 objects for specific commodities (Copper, Aluminum, PVC Resin, Galvanized Steel). Each object must have: "symbol" (e.g. "LME.Cu"), "name", "price" (approximate current INR price formatted as string, e.g. "₹715.50"), "trend" (percentage trend string, e.g. "+1.2%"), and "up" (boolean true if trend is positive, false if negative).

RETURN ONLY RAW JSON. NO MARKDOWN.`;

export async function getMarketInsights(): Promise<{ data: MarketData; stale: boolean }> {
  if (cached && Date.now() - lastFetchedAt < CACHE_TTL_MS) {
    console.log('[MARKET_INTEL] Serving cached unified market data.');
    return { data: cached, stale: false };
  }

  try {
    console.log('[MARKET_INTEL] Fetching live market data via AI...');
    const aiResponse = await getHelperBotResponse(PROMPT, null, []);
    const cleanJson = aiResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    const parsed = JSON.parse(cleanJson);

    if (parsed.insights && parsed.commodities) {
      cached = parsed as MarketData;
      lastFetchedAt = Date.now();
      return { data: cached, stale: false };
    }

    return { data: cached ?? OFFLINE_FALLBACK, stale: true };
  } catch (err: any) {
    console.error('🔥 [MARKET_INTEL] Fetch Error:', err.message);
    return { data: cached ?? OFFLINE_FALLBACK, stale: true };
  }
}
